version: '2'
services:

  campus:
    container_name: "campus"
    image: "nginx"
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/nginx/log/:/var/log/nginx/
      - ./data/nginx/html:/usr/share/nginx/html

    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  filebeat:
    container_name: "filebeat"
    image: "docker.elastic.co/beats/filebeat:6.2.4"
    volumes:
      # OJO: chown root. ./conf/filebeat/filebeat.yml
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    volumes_from:
      - campus
    ports:
      - 80:80
      - 443:443
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    depends_on: 
      - campus
      - logstash


  logstash:
    container_name: "logstash"
    image: "docker.elastic.co/logstash/logstash:6.2.4"
    volumes:
      - ./conf/logstash/pipeline:/usr/share/logstash/pipeline
      - ./conf/logstash/config:/usr/share/logstash/config
      - ./conf/logstash/patterns:/usr/share/logstash/patterns
    ports:
      - 5044:5044
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    depends_on: 
      - elastic


  kibana:
    container_name: "kibana"
    image: "docker.elastic.co/kibana/kibana-oss:6.2.4"
    volumes:
      - ./conf/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
      - 5601:5601
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    depends_on: 
      - elastic

  elastic:
    # sudo sysctl -w vm.max_map_count=262144
    container_name: "elastic"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4"
    environment:
      - cluster.name=pfc-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1